#!/bin/sh
# DEBUG CONFIG 为了支持boost stacktrace
clang++ main.cpp -lfmt -std=c++23 -O0 -rdynamic -g -o build/scheme && build/scheme
# RELEASE CONFIG
# g++ main.cpp -lfmt -std=c++20 -s -o build/scheme && build/scheme